fix(stepper): adds styles for windows hcm
swisspost/common-web-frontend pull request #164
Opened 2022-07-14 12:42 UTC by oliverschuerch

2022-07-14 13:20 UTC, gfellerph requested changes
@oliverschuerch can you decrease the line thickness to 2px to be more consistent with other borders?

2022-07-15 07:37 UTC, oliverschuerch commented
@gfellerph I fixed the indicator-size in forced-color/high-contrast mode, to match the size in normal mode.
This made some of your suggestions obsolete. Please have a look.

2022-07-15 07:59 UTC, gfellerph approved these changes
Looks good now!

2022-07-15 07:59 UTC, gfellerph commented on .changeset/hungry-news-swim.md
> +adds styles for component stepper in forced-color/high-contrast mode
```suggestion
Adds styles for component stepper in forced-color/high-contrast mode
```

2022-07-15 08:07 UTC, merged